name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-bun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0.9'
          mongodb-replica-set: rs0
          mongodb-port: 42069

      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: '7'
          number of databases: 10

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.1.1'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run integration tests with Bun
        run: bun test:integration
        env:
          DB_PORT: 42069
          NODE_ENV: test

  test-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0.9'
          mongodb-replica-set: rs0
          mongodb-port: 42069

      - uses: zhulik/redis-action@1.1.0
        with:
          redis version: '7'
          number of databases: 10

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run integration tests with Node
        run: npm run test:integration
        env:
          DB_PORT: 42069
          NODE_ENV: test
